account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/', views.register_view, name='register'),
    path('', views.index, name='index'),
]

admin_panel/urls.py
from django.urls import path
from . import views

app_name = 'admin_panel'

urlpatterns = [
    # Panel principal
    path('dashboard/', views.admin_dashboard_view, name='dashboard'),    
    # CRUD de Usuarios
    path('usuarios/', views.listar_usuarios_view, name='listar_usuarios'),
    path('usuarios/editar/<str:username>/', views.editar_usuario_view, name='editar_usuario'),
    path('usuarios/eliminar/<str:username>/', views.eliminar_usuario_view, name='eliminar_usuario'),
]

healthtrack/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


def redirect_to_login(request):
    return redirect('account:login')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('home/', include('home.urls')),
    path('habitos/', include('seguimiento.urls')),
    path('', redirect_to_login),  # Redirige la raíz al login
    path('admin_panel/', include('admin_panel.urls')), 
    path('professional_panel/', include('professional_panel.urls')),
    path('perfiles/', include('perfiles.urls')),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('perfil/completar/', views.completar_perfil_view, name='completar_perfil'),
    path('mensajes/', views.mensajes_view, name='mensajes'),
]

perfiles/urls.py
from django.urls import path
from . import views

app_name = 'perfiles' 

urlpatterns = [
    path('', views.mi_perfil_view, name='ver_perfil'),
    path('editar/', views.editar_perfil_view, name='editar_perfil'),
    path('password/', views.cambiar_password_view, name='cambiar_password'),
]

seguimiento/urls.py
from django.urls import path
from . import views  

app_name = 'habitos'

urlpatterns = [
    path('crear_habito/', views.crear_habito_view, name='crear_habito'),
    path('registro_habito/', views.registro_habitos_view, name='registro_habito'),
    path('mi_progreso/', views.mi_progreso_view, name='mi_progreso'),
    path('eliminar/<str:id_habito>/', views.eliminar_habito_view, name='eliminar_habito'),
]

healthtrack/templates/includes/footer.html
<footer class="bg-dark text-white mt-5 p-4 text-center">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="mb-0">&copy; {% now "Y" %} Health Track - Proyecto Final Backend.</p>
                <p class="mb-0 small">
                    Arquitectura Híbrida: Django + Node.js + Firestore.
                </p>
                </div>
        </div>
    </div>
</footer>

healthtrack/templates/includes/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
    <div class="container-fluid">
        
        <a class="navbar-brand d-flex align-items-center" href="{% url 'home:index' %}">
            <span class="fs-4 fw-bold">HealthTrack</span>
            </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Inicio</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'habitos:crear_habito' %}">Hábitos</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">Cerrar Sesión</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Iniciar Sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

healthtrack/templates/includes/nav_admin.html
<nav class="navbar navbar-expand-lg navbar-dark {{ NAV_CLASS }} shadow-sm">
    <div class="container-fluid">
        
        <a class="navbar-brand d-flex align-items-center" href="{% url 'admin_panel:dashboard' %}">
            <span class="fs-4 fw-bold">HealthTrack - ADMIN</span>
            </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin_panel:dashboard' %}">Inicio</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'perfiles:ver_perfil' %}">Mi Perfil</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">Cerrar Sesión</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Iniciar Sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

healthtrack/templates/includes/nav_profesional.html
<nav class="navbar navbar-expand-lg navbar-dark {{ NAV_CLASS }} shadow-sm">
    <div class="container-fluid">

        <a class="navbar-brand d-flex align-items-center" href="{% url 'professional_panel:dashboard' %}">
            <span class="fs-4 fw-bold">HealthTrack - PRO</span>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'professional_panel:dashboard' %}">Panel Profesional</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'perfiles:ver_perfil' %}">Mi Perfil</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:logout' %}">Cerrar Sesión</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'account:login' %}">Iniciar Sesión</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

healthtrack/templates/includes/nav_user.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary shadow-sm">
    <div class="container-fluid">
        
        <a class="navbar-brand d-flex align-items-center" href="{% url 'home:index' %}">
            <span class="fs-4 fw-bold">HealthTrack - USER</span>
            </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'home:index' %}">Inicio</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'habitos:registro_habito' %}">Mis Hábitos</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'habitos:crear_habito' %}">Hábitos</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'habitos:mi_progreso' %}">Mi Progreso</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'perfiles:ver_perfil' %}">Mi Perfil</a>
                    </li>
                    
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:logout' %}">Cerrar Sesión</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account:login' %}">Iniciar Sesión</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>